POST http://localhost:3000/administrativo/registro
content-type: application/json

{
    "nome": "Jorge",
    "matricula": "0001",
    "cpf": "123.456.789-01",
    "status": "ativo",
    "dataNasc": "1980-01-01",
    "email": "coordenador1@gmail.com",
    "password": "123456"
}

###

GET http://localhost:3000/professor
content-type: application/json

{
    "nome": "9º Ano",
    "turno": "Manhã"
}

###

GET http://localhost:3000/administrativo/

###

PATCH http://localhost:3000/disciplina/1
Content-Type: application/json
{
  "status": "inativa"
}

### 
GET http://localhost:3000/matricula-disciplina

###
GET http://localhost:3000/turma-professor-disciplina

###
GET http://localhost:3000/submissao-avaliacao/professor/avaliacao/1
professor-id: 1